//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace ChangeRequest_v1_0 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ChangeRequestAbstraction", Namespace="", IsNullable=false)]
    public partial class ChangeRequestAbstractionType {
        
        private ChangeRequestType[] changeRequestsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ChangeRequest", IsNullable=false)]
        public ChangeRequestType[] ChangeRequests {
            get {
                return this.changeRequestsField;
            }
            set {
                this.changeRequestsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeRequestType {
        
        private string descriptionField;
        
        private string nameField;
        
        private ChangeRequestTypePriority priorityField;
        
        private ChangeRequestTypeChangeType changeTypeField;
        
        private System.DateTime dueDateField;
        
        private bool dueDateFieldSpecified;
        
        public ChangeRequestType() {
            this.priorityField = ChangeRequestTypePriority.Undefined;
            this.changeTypeField = ChangeRequestTypeChangeType.Undefined;
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ChangeRequestTypePriority.Undefined)]
        public ChangeRequestTypePriority priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ChangeRequestTypeChangeType.Undefined)]
        public ChangeRequestTypeChangeType changeType {
            get {
                return this.changeTypeField;
            }
            set {
                this.changeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDateSpecified {
            get {
                return this.dueDateFieldSpecified;
            }
            set {
                this.dueDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ChangeRequestTypePriority {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Critical,
        
        /// <remarks/>
        Urgent,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ChangeRequestTypeChangeType {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        ChangeToExistingFunctionality,
        
        /// <remarks/>
        NewFunctionality,
    }
}
